### ISSUE TITLE
Starter project only works with pre-configured TestRPC

### ISSUE THREAD

**Issue by brennanerbz** [0xProject/0x-starter-project#2]
What's needed to run the starter project with a ganache provider? Or even Ropsten with Infura?

**Comment by fabioberger** [comment]
@brennanerbz 

In order to use ganache, you would need to manually run the [0x smart contract](https://github.com/0xProject/0x.js/tree/development/packages/contracts) migrations (`yarn migrate`) locally after starting the Ganache TestRPC daemon.

If you want to use Ropsten with Infura, you need to pass in the 0x smart contract addresses deployed on Ropsten at 0x.js instantiation:

```
const provider = new Web3.providers.HttpProvider('https://ropsten.infura.io/');

// Instantiate 0x.js instance
const configs = {
    networkId: TESTRPC_NETWORK_ID,
    exchangeContractAddress: '0x479cc461fecd078f766ecc58533d6f69580cf3ac',
    tokenRegistryContractAddress: '0x6b1a50f0bb5a7995444bd3877b22dc89c62843ed',
    tokenTransferProxyContractAddress: '0x4e9aad8184de8833365fea970cd9149372fdf1e6',
    zrxContractAddress: '0xa8e9fa8f91e5ae138c74648c9c304f1c75003a8d',
};
const zeroEx = new ZeroEx(provider, configs);
```

The deployed 0x smart contract address for each network can be found [here](https://0xproject.com/wiki#Deployed-Addresses).

**Comment by dekz** [comment]
This now works with the Ganache snapshot, Ropsten and Kovan. Let me know if you have any further issues.
